### ISSUE TITLE
"get ready" looks bad

### ISSUE THREAD

**Issue by adbenitez** [DeltaZen/super-bunny#2]
it would be better shorter "start" or "play"(like the original), to avoid such layout issues on phones, and also "get ready" reads like "wait..." to me
 
![image](https://github.com/DeltaZen/super-bunny/assets/24558636/8800f18c-1d59-4eb3-b33a-688c043bfeaa)

**Comment by adbenitez** [comment]
also the selfName in the "Foo strikes back" can cause issue, maybe also strike the name from there

**Comment by r10s** [comment]
> also the selfName in the "Foo strikes back" can cause issue, maybe also strike the name from there

i added that for the fun of it. the typo and truncation may indeed be weird, but well, the whole game and style is :) i did not dived further, it's okay, it's art

for "get ready": yes, we can use PLAY
